FROM openjdk:11-jre

COPY ./node_exporter-1.1.2.linux-amd64.tar.gz /node_exporter-1.1.2.linux-amd64.tar.gz
RUN tar -xzf ./node_exporter-1.1.2.linux-amd64.tar.gz
#RUN nohup bash -c "/node_exporter-*.*-amd64/node_exporter &"
#put nohup hack in spp-example-webapp-boot jar

ADD ./spp-example-webapp-boot-1.0-SNAPSHOT.zip /spp-example-webapp-boot-1.0-SNAPSHOT.zip

COPY ./apache-skywalking-apm-es7-8.5.0.tar.gz /apache-skywalking-apm-es7-8.5.0.tar.gz
RUN tar -xzf ./apache-skywalking-apm-es7-8.5.0.tar.gz

ADD ./agent.config /apache-skywalking-apm-bin-es7/agent/config/agent.config
#ADD ./customize_enhance.xml /apache-skywalking-apm-bin/agent/config/customize_enhance.xml

ENV JAVA_OPTS="-javaagent:/apache-skywalking-apm-bin-es7/agent/skywalking-agent.jar"
ENV SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap:11800

RUN unzip *.zip
CMD ["./spp-example-webapp-boot-1.0-SNAPSHOT/bin/spp-example-webapp"]