version: '3.3'
services:
  skywalking-oap:
    container_name: skywalking-oap
    hostname: skywalking-oap
    restart: on-failure
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "11800:11800"
      - "12800:12800"
    environment:
      - SW_STORAGE=postgresql
      - SW_JDBC_URL=jdbc:postgresql://postgres:5432/postgres
      - SW_DATA_SOURCE_USER=postgres
      - SW_DATA_SOURCE_PASSWORD=123456
      - SW_OTEL_RECEIVER=default
      - SW_OTEL_RECEIVER_ENABLED_OC_RULES=vm
    build:
      context: .
      dockerfile: Dockerfile-skywalking-oap
  spp-example-webapp:
    container_name: spp-example-webapp
    hostname: spp-example-webapp
#    ports:
#      - "9100:9100"
    depends_on:
      - skywalking-oap
      - otel-collector
    links:
      - skywalking-oap
      - otel-collector
    build:
      context: .
      dockerfile: Dockerfile-spp-example-webapp
  skywalking-ui:
    image: apache/skywalking-ui:8.4.0
    container_name: skywalking-ui
    hostname: skywalking-ui
    ports:
      - "9999:8080"
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap
    environment:
      - SW_OAP_ADDRESS=skywalking-oap:12800
  postgres:
    image: postgres:9.6.21
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  superset:
    container_name: superset
    hostname: superset
    ports:
      - "8888:8088"
    build:
      context: .
      dockerfile: Dockerfile-superset
  otel-collector:
    container_name: otel-collector
    hostname: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    build:
      context: .
      dockerfile: Dockerfile-otel-collector
#    ports:
#      - "13133:13133" # health_check extension
#      - "55678"       # OpenCensus receiver